### ISSUE TITLE
Unable to find theme file for 'horizon'

### ISSUE THREAD

**Issue by Redcroft** [aodhneine/horizon-theme.el#6]
Hi,
Installing via use-package (using straight.el) i get the following error

`Error (use-package): horizon-theme/:config: Unable to find theme file for ‘horizon’`

however the theme doas appear to load, it doesnt showup inside the load-theme menu

Cheers

**Comment by aodhneine** [comment]
Thanks for reporting this!
It seems to work if you use

```emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(use-package horizon-theme)
```
or
```emacs-lisp
(straight-use-package 'use-package)
(use-package horizon-theme
  :straight t)
```

Could you check if using any of the above snippets solves this issue? If not, please post your `init.el` or `.emacs` file.

It doesn't show in `M-x load-theme`, nor does `(load-theme horizon-theme t)` work, but I expect it's because straight.el doesn't know that this is theme package, so it doesn't add it to the `custom-theme-load-path`.

**Comment by Redcroft** [comment]
Hi,

removing load-theme horizon removes the error, and just doing  (use-package horizon-theme) does load the theme

Thanks

**Comment by aodhneine** [comment]
Great, I'm happy that it worked as I expected! I will update the README to include better information about installation process, so I will consider this issue as resolved.
